// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	resource "github.com/PG2000/artifacthub-resource"
)

type FakeArtifactHub struct {
	ListHelmVersionStub        func(resource.Package, string) (resource.HelmVersion, error)
	listHelmVersionMutex       sync.RWMutex
	listHelmVersionArgsForCall []struct {
		arg1 resource.Package
		arg2 string
	}
	listHelmVersionReturns struct {
		result1 resource.HelmVersion
		result2 error
	}
	listHelmVersionReturnsOnCall map[int]struct {
		result1 resource.HelmVersion
		result2 error
	}
	ListVersionsStub        func(resource.Package) ([]resource.Version, error)
	listVersionsMutex       sync.RWMutex
	listVersionsArgsForCall []struct {
		arg1 resource.Package
	}
	listVersionsReturns struct {
		result1 []resource.Version
		result2 error
	}
	listVersionsReturnsOnCall map[int]struct {
		result1 []resource.Version
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeArtifactHub) ListHelmVersion(arg1 resource.Package, arg2 string) (resource.HelmVersion, error) {
	fake.listHelmVersionMutex.Lock()
	ret, specificReturn := fake.listHelmVersionReturnsOnCall[len(fake.listHelmVersionArgsForCall)]
	fake.listHelmVersionArgsForCall = append(fake.listHelmVersionArgsForCall, struct {
		arg1 resource.Package
		arg2 string
	}{arg1, arg2})
	stub := fake.ListHelmVersionStub
	fakeReturns := fake.listHelmVersionReturns
	fake.recordInvocation("ListHelmVersion", []interface{}{arg1, arg2})
	fake.listHelmVersionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeArtifactHub) ListHelmVersionCallCount() int {
	fake.listHelmVersionMutex.RLock()
	defer fake.listHelmVersionMutex.RUnlock()
	return len(fake.listHelmVersionArgsForCall)
}

func (fake *FakeArtifactHub) ListHelmVersionCalls(stub func(resource.Package, string) (resource.HelmVersion, error)) {
	fake.listHelmVersionMutex.Lock()
	defer fake.listHelmVersionMutex.Unlock()
	fake.ListHelmVersionStub = stub
}

func (fake *FakeArtifactHub) ListHelmVersionArgsForCall(i int) (resource.Package, string) {
	fake.listHelmVersionMutex.RLock()
	defer fake.listHelmVersionMutex.RUnlock()
	argsForCall := fake.listHelmVersionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeArtifactHub) ListHelmVersionReturns(result1 resource.HelmVersion, result2 error) {
	fake.listHelmVersionMutex.Lock()
	defer fake.listHelmVersionMutex.Unlock()
	fake.ListHelmVersionStub = nil
	fake.listHelmVersionReturns = struct {
		result1 resource.HelmVersion
		result2 error
	}{result1, result2}
}

func (fake *FakeArtifactHub) ListHelmVersionReturnsOnCall(i int, result1 resource.HelmVersion, result2 error) {
	fake.listHelmVersionMutex.Lock()
	defer fake.listHelmVersionMutex.Unlock()
	fake.ListHelmVersionStub = nil
	if fake.listHelmVersionReturnsOnCall == nil {
		fake.listHelmVersionReturnsOnCall = make(map[int]struct {
			result1 resource.HelmVersion
			result2 error
		})
	}
	fake.listHelmVersionReturnsOnCall[i] = struct {
		result1 resource.HelmVersion
		result2 error
	}{result1, result2}
}

func (fake *FakeArtifactHub) ListVersions(arg1 resource.Package) ([]resource.Version, error) {
	fake.listVersionsMutex.Lock()
	ret, specificReturn := fake.listVersionsReturnsOnCall[len(fake.listVersionsArgsForCall)]
	fake.listVersionsArgsForCall = append(fake.listVersionsArgsForCall, struct {
		arg1 resource.Package
	}{arg1})
	stub := fake.ListVersionsStub
	fakeReturns := fake.listVersionsReturns
	fake.recordInvocation("ListVersions", []interface{}{arg1})
	fake.listVersionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeArtifactHub) ListVersionsCallCount() int {
	fake.listVersionsMutex.RLock()
	defer fake.listVersionsMutex.RUnlock()
	return len(fake.listVersionsArgsForCall)
}

func (fake *FakeArtifactHub) ListVersionsCalls(stub func(resource.Package) ([]resource.Version, error)) {
	fake.listVersionsMutex.Lock()
	defer fake.listVersionsMutex.Unlock()
	fake.ListVersionsStub = stub
}

func (fake *FakeArtifactHub) ListVersionsArgsForCall(i int) resource.Package {
	fake.listVersionsMutex.RLock()
	defer fake.listVersionsMutex.RUnlock()
	argsForCall := fake.listVersionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeArtifactHub) ListVersionsReturns(result1 []resource.Version, result2 error) {
	fake.listVersionsMutex.Lock()
	defer fake.listVersionsMutex.Unlock()
	fake.ListVersionsStub = nil
	fake.listVersionsReturns = struct {
		result1 []resource.Version
		result2 error
	}{result1, result2}
}

func (fake *FakeArtifactHub) ListVersionsReturnsOnCall(i int, result1 []resource.Version, result2 error) {
	fake.listVersionsMutex.Lock()
	defer fake.listVersionsMutex.Unlock()
	fake.ListVersionsStub = nil
	if fake.listVersionsReturnsOnCall == nil {
		fake.listVersionsReturnsOnCall = make(map[int]struct {
			result1 []resource.Version
			result2 error
		})
	}
	fake.listVersionsReturnsOnCall[i] = struct {
		result1 []resource.Version
		result2 error
	}{result1, result2}
}

func (fake *FakeArtifactHub) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listHelmVersionMutex.RLock()
	defer fake.listHelmVersionMutex.RUnlock()
	fake.listVersionsMutex.RLock()
	defer fake.listVersionsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeArtifactHub) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resource.ArtifactHub = new(FakeArtifactHub)
